//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopdongho.Content.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<int> Upsate_by { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public int Status { get; set; }
    }
}
